### ISSUE TITLE
html-template generates anonymous-schemas

### ISSUE THREAD

**Issue by djdjoko** [asyncapi/html-template#239]
Hello,

I am trying to generate html documentation with the html-template (Windows 10.0) but it renders additional properties to the schemas in the html such as <anonymous-schema-1>, <anonymous-schema-2> and <anonymous-schema-3>

I have tried running the following command to generate the html template.
ag https://raw.githubusercontent.com/asyncapi/asyncapi/v2.1.0/examples/simple.yml @asyncapi/html-template -o output

When I run it via the docker example, I get the same behaviour. 

![image](https://user-images.githubusercontent.com/902354/126501126-0a4aa41f-120f-449d-b33b-ddee3baae16f.png)

Could you please help me with this?

Thanks

**Comment by magicmatatjahu** [comment]
@djdjoko Hi! It's not a bug, but intentional decision. We render each schemas (not only in the `components/schemas` section) but also in the other, like plain schemas in the `message/payload` etc (by this you see `anonymous...`). As I look at it, it looks pretty weird and will only cause more and more problems from UX side, so I'm going to create a PR to fix this right now. Thanks for the issue!

**Comment by djdjoko** [comment]
Hi, thanks for the quick reply. I am trying to write a complex schema with multiple files and this issue seems to compound when I reference to other files:


```
# simple.yml
asyncapi: '2.1.0'
info:
  title: Account Service
  version: 1.0.0
  description: This service is in charge of processing user signups
channels:
  user/signedup:
    subscribe:
      message:
        $ref: './simple_messages.yml'
```

```
# simple_messages.yml
summary: Receive quote updates on a given symbol.
payload:
  type: object
  properties:
    displayName:
      type: string
      description: Name of the user
    email:
      type: string
      format: email
      description: Email of the use   

```

The output it generates looks like this:

![image](https://user-images.githubusercontent.com/902354/126521067-29c9fb1b-f673-4bde-b54b-9bf97c73f845.png)
