### ISSUE TITLE
Header name should default to Authorization when auth type is http

### ISSUE THREAD

**Issue by derberg** [asyncapi/html-template#28]
@fmvilas commented on [Wed Jan 22 2020](https://github.com/asyncapi/generator/issues/201)

**Applies to:** HTML and Markdown templates.

---

Given this security definition:

```yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: The JWT for authorizing against the backend. Needs to be obtained through the authentication route.
```

It's not possible to define the name of the header but the default value "Authorization" should be shown. At least until we fix [this](https://github.com/asyncapi/asyncapi/issues/307). Currently, we got this:

![image](https://user-images.githubusercontent.com/242119/72885595-847c6900-3d08-11ea-9936-a6174286b1f5.png)

Thanks @luca-moser for reporting the bug 🙌 

---

@github-actions[bot] commented on [Wed May 13 2020](https://github.com/asyncapi/generator/issues/201#issuecomment-627664589)

This issue has been automatically marked as stale because it has not had recent activity :sleeping:
It will be closed in 30 days if no further activity occurs. To unstale this issue, add a comment with detailed explanation. 
Thank you for your contributions :heart:
