### ISSUE TITLE
For Avro payload format, if examples message is specified in yaml, html generator fails

### ISSUE THREAD

**Issue by jyotibhangale** [asyncapi/html-template#289]
#### Describe the bug
For Avro payload format, if examples block is specified in yaml, html generator fails with error

#### How to Reproduce
 ag .\user_signedup.yaml @asyncapi/html-template

Something went wrong:
Error: There were errors validating the AsyncAPI document.
    at parse (C:\Users\jyotibhangale\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\parser\lib\parser.js:100:23)
    at Generator.generateFromString (C:\Users\jyotibhangale\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:265:22)
    at C:\Users\jyotibhangale\AppData\Roaming\npm\node_modules\@asyncapi\generator\cli.js:154:9
[
    {
        "title": "/channels/transactions/subscribe/message should have required property '$ref'",
        "location": {
            "jsonPointer": "/channels/transactions/subscribe/message",
            "startLine": 22,
            "startColumn": 7,
            "startOffset": 623,
            "endColumn": null
        }
    },
    {
        "title": "/channels/transactions/subscribe/message should NOT have additional properties",
        "location": {
            "jsonPointer": "/channels/transactions/subscribe/message/description",
            "startLine": 23,
            "startColumn": 9,
            "startOffset": 641,
            "endLine": 23,
            "endColumn": 69,
            "endOffset": 701
        }
    },

....

- Screenshots
- Link to GitHub repository with project that has issues
- asyncapi spec file available at:
https://raw.githubusercontent.com/shavo007/kafka-tutorial/main/asyncapi/src/main/resources/avro/io/confluent/examples/clients/basicavro/payment-avro-ref-asyncapi.yaml

#### Expected behavior
Should generate html document from asyncapi spec.

**Comment by magicmatatjahu** [comment]
@jyotibhangale Hello. It's not a problem with html-template but with your AsyncAPI document. Extended examples with `summary` field is from `2.1.0` version of spec, and also `examples` are an array of object, not array of objects with one field (ad id), so you should change your examples to the:

```yaml
        examples:
          - name: payment
            summary: Example payment
            payload: |-
              {"id": "{{randomString(32)}}", "amount": {{randomInt(25, 50)}}}
```

shape. Also, please don't write payload as string (atm you write as string), but as object:

```yaml
payload: 
  id: "{{randomString(32)}}"
  amount: {{randomInt(25, 50)}}
```
 
And most important, please change version of spec to `2.1.0`, but better will be to the `2.2.0` :)

More info: https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageExampleObject

**Comment by magicmatatjahu** [comment]
@jyotibhangale I will close issue, please reopen it if you have more questions/problems.

**Comment by magicmatatjahu** [comment]
@jyotibhangale Did you change also the version of spec?

Here is a valid spec:

```yaml
asyncapi: '2.2.0'
id: 'urn:io.confluent.examples.payment'
info:
  title: Payment Avro API
  version: 0.1.2
  description: Sample AsyncAPI for user signedup events defined using Avro
  contact:
    name: Shane Lee
    url: https://github.com/shavo007
    email: x@gmail.com
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
defaultContentType: application/json
tags:
  - name: payment
servers:
    production:
      url: broker.mycompany.com
      protocol: kafka
      description: This is "My Company" broker.
channels:
  transactions:
    description: The topic on which user signed up events may be consumed
    subscribe:
      summary: Receive informations about payments
      description: Hello
      operationId: receivedPayment
      message:
        description: An event describing that a user just signed up.
        bindings:
          kafka:
            key:
              type: string
              description: id of the payment
        contentType: avro/binary
        schemaFormat: application/vnd.apache.avro+json;version=1.9.0
        payload:
          $ref: './Payment.avsc'
        examples:
          - name: payment
            summary: Example payment
            payload:
              id: "{{randomString(32)}}"
              amount: "{{randomInt(25, 50)}}"
```

The problem may also be that you are using an old version of the generator/template. Please install the latest generator:

```bash
npm i -g @asyncapi/generator
```

and use the latest version of template:

```bash
ag <your-spec> @asyncapi/html-template@0.24.0 <rest>
```

Let me know if everything is good :)
