### ISSUE TITLE
can't build with Yarn 4 (pnp) in 3.0.0

### ISSUE THREAD

**Issue by woylie** [asyncapi/html-template#454]
#### Describe the bug
After upgrading from 0.28.4 to 1.0.0, the asyncapi HTML documentation cannot be built with Yarn 3 in pnp mode anymore.

#### How to Reproduce

1. `yarn init -2`
2. add these lines to `.yarnrc.yml`:

```yml
nodeLinker: pnp
packageExtensions:
  "@asyncapi/parser@*":
    dependencies:
      "@stoplight/types": "^13.9.1"
      "@stoplight/json": "^3.20.2"
      "@stoplight/spectral-ref-resolver": "^1.0.3"
      "@stoplight/json-ref-readers": "^1.2.2"
```

3. add these lines to `package.json`:

```json
"scripts": {
    "asyncapi": "ag asyncapi.yml @asyncapi/html-template"
  },
```

4. `yarn add @asyncapi/generator @asyncapi/html-template`
5. save random asyncapi document as `asyncapi.yml`

```yml
asyncapi: 2.6.0
info:
  title: Hello world application
  version: "0.1.0"
channels:
  hello:
    publish:
      message:
        payload:
          type: string
          pattern: "^hello .+$"
```

6. run `yarn asyncapi`

This will produce the following output:

```
Something went wrong:
Error: EROFS: read-only filesystem, mkdir '/node_modules/@asyncapi/html-template/__transpiled'
    at makeError$1 (/Users/me/project/assets/.pnp.cjs:14658:24)
    at EROFS (/Users/me/project/assets/.pnp.cjs:14685:10)
    at ZipFS.mkdirSync (/Users/me/project/assets/.pnp.cjs:16597:13)
    at ZipFS.mkdirpSync (/Users/me/project/assets/.pnp.cjs:14879:16)
    at ZipFS.mkdirSync (/Users/me/project/assets/.pnp.cjs:16595:19)
    at ZipFS.mkdirPromise (/Users/me/project/assets/.pnp.cjs:16591:17)
    at /Users/me/project/assets/.pnp.cjs:17658:26
    at /Users/me/project/assets/.pnp.cjs:17840:81
    at ZipOpenFS.getZipPromise (/Users/me/project/assets/.pnp.cjs:17947:22)
    at ZipOpenFS.makeCallPromise (/Users/me/project/assets/.pnp.cjs:17840:23)
```

#### Expected behavior
The documentation should still be built.
