### ISSUE TITLE
Missing elements from deeply nested objects

### ISSUE THREAD

**Issue by kostisthomaidis** [asyncapi/html-template#58]
#### Describe the bug
Hi everyone! We are developing a car dealership application and we are trying to incorporate AsyncAPI to our stack.
Using the AsyncAPI Playground to test the file, I found that some nested objects (3 levels deep) were not created in full.
After cloning the project and debugging locally, I traced that the file was properly parsed and could find it as context up to this point in the call stack:
![Screenshot from 2020-09-07 18-13-32](https://user-images.githubusercontent.com/19896544/92401260-f8ec0700-f135-11ea-878a-d8b33fdcd524.png)
![Screenshot from 2020-09-07 18-12-35](https://user-images.githubusercontent.com/19896544/92401284-05705f80-f136-11ea-86ea-2108750be506.png)
However, I am not very familiar with JS and could use some help with this.

#### How to Reproduce
- Visit https://playground.asyncapi.io/
- Paste the following yaml file:
[carDealership-asyncapi.zip](https://github.com/asyncapi/html-template/files/5183485/carDealership-asyncapi.zip)

An example of the bug lies in the component payload -> previousOwners -> individual, under jsonMessage. The component has more properties, but they have not been rendered.

#### Expected behavior
Properties of deeply nested objects (like the example above) should be rendered.

**Comment by fmvilas** [comment]
Hey @kostisthomaidis! I found the problem here. It's actually a bug on your AsyncAPI definition:

```yaml
    individual:
      type: object
      firstName:
        type: string
        description: First name of individual.
      lastName:
        type: string
        description: Last name of individual.
      employment:
        type: string
        description: Employment of individual
      usage:
        type: string
        description: Usage of car by owner
        enum:
          - Holiday
          - Work
          - Commute
      mileage:
        type: integer
        description: Mileage under this owner
```

You're missing the `properties` key here. It should be:

```yaml
    individual:
      type: object
      properties: # <== Notice this field
        firstName:
          type: string
          description: First name of individual.
        lastName:
          type: string
          description: Last name of individual.
        employment:
          type: string
          description: Employment of individual
        usage:
          type: string
          description: Usage of car by owner
          enum:
            - Holiday
            - Work
            - Commute
        mileage:
          type: integer
          description: Mileage under this owner
```

The reason it's not failing is that it's not illegal to place disparate fields on a JSON Schema object.

Hope it helps!
