### ISSUE TITLE
Blank HTML generated - but correct schema present in Javascript objects

### ISSUE THREAD

**Issue by frankjkelly** [asyncapi/html-template#718]
Could be a bug could be just me as a newbie

Just got around from updating from the old npm and ag way of doing things to the new way.
Since I am on Apple Silicon and hit some issues I decided to use docker and mount all the files I needed

```
docker run --rm -it --user=root \
-v ./specs/services/compute.yml:/app/asyncapi.yml \
-v ./specs/schemas/schemas.yml:/schemas/schemas.yml \
-v ./specs/messages/messages.yml:/messages/messages.yml \
-v ./build/generated-docs/html/compute:/app/output \
asyncapi/cli generate fromTemplate -o /app/output /app/asyncapi.yml @asyncapi/html-template@3.2.0 --use-new-generator --force-write
```

I fixed all the issues in my schema and it runs without complaint

```
Generation in progress. Keep calm and wait a bit
[BABEL] Note: The code generator has deoptimised the styling of /libraries/node_modules/generator-v2/node_modules/@asyncapi/html-template/template/js/asyncapi-ui.min.js as it exceeds the max of 500KB.
Check out your shiny new generated files at /app/output.
```

but when I look at the generated output I see a header and no content.  Any ideas? Using  `@asyncapi/html-template@3.0.0` I can see the full schema in the page source - see below

![Image](https://github.com/user-attachments/assets/0aa99af1-7a18-4b7e-a480-f677a4a00e03)

![Image](https://github.com/user-attachments/assets/5922d9bc-a9ca-4a75-817c-9571d17f2d26)

Environment: Apple Silicon

![Image](https://github.com/user-attachments/assets/b3215004-b126-4654-9ee0-2aad16a32d8d)

Please let me know if you need any more information

**Comment by frankjkelly** [comment]
FYI I'm a JS newbie too but the first error I see in the JavaScript is here. No idea if this is helpful or not.

![Image](https://github.com/user-attachments/assets/2af1098d-f87a-4bc6-83ac-978dd22193f3)

**Comment by derberg** [comment]
hey there, did you try other commands, like instead of `generate fromTemplate -o /app/output /app/asyncapi.yml @asyncapi/html-template@3.2.0 --use-new-generator --force-write` just do `validate` to see if other outputs work?

but to be honest - your command is completely fine so my guess there is something missing in your AsyncAPI document - maybe it is valid but do not provide the necessary data. Can you share it? best if you put it in https://studio.asyncapi.com/ and then grab a link using its sharing functionality and put a link here. Or just paste the document as markdown code here - whatever you prefer.

**Comment by frankjkelly** [comment]
@derberg Thanks - unfortunately I'd be uploading some pretty sensitive information.
I  think I am going to take another approach and roll back my changes back to `asyncapi:2.0.0` and work through the errors

What's odd is I get so many errors in some schemas and not in others
```
Diagnostic err: Operation should have an "operationId" field defined. in path ["channels","persistent://platform2/event/interaction","publish"] starting L15 C12, ending L26 C78
Diagnostic err: Property "oneOf" is not expected to be here in path ["channels","persistent://platform2/event/interaction","publish","message","oneOf"] starting L17 C14, ending L26 C78
Diagnostic err: "8" property must have required property "oneOf" in path ["components","messages","intervalNext"] starting L383 C17, ending L479 C36
Diagnostic err: "8" property must match "then" schema in path ["components","messages","intervalNext"] starting L383 C17, ending L479 C36
Diagnostic err: Property "name" is not expected to be here in path ["components","messages","intervalNext","name"] starting L384 C12, ending L384 C29
Diagnostic err: Property "title" is not expected to be here in path ["components","messages","intervalNext","title"] starting L385 C13, ending L385 C32
Diagnostic err: Property "summary" is not expected to be here in path ["components","messages","intervalNext","summary"] starting L386 C15, ending L386 C28
Diagnostic err: Property "description" is not expected to be here in path ["components","messages","intervalNext","description"] starting L387 C19, ending L387 C138
Diagnostic err: Property "payload" is not expected to be here in path ["components","messages","intervalNext","payload"] starting L390 C14, ending L479 C36
Diagnostic err: "allOf" property type must be object,boolean in path ["components","messages","intervalNext","payload","properties","payload","properties","previousInterval","properties","allOf"] starting L403 C24, ending L404 C92
Diagnostic err: must be object,boolean in path ["components","messages","intervalNext","payload","properties","payload","properties","previousInterval","properties","allOf"] starting L403 C24, ending L404 C92
Diagnostic err: Property "headers" is not expected to be here in path ["components","schemas","headers"] starting L125 C12, ending L130 C85
Generation failed
Generator Error: Input is not a correct AsyncAPI document so it cannot be processed.
```

Is there some way to figure out which errors are critical e.g. the one's with `should` seem like they are warnings. The others I guess are errors.

What's really odd is this one
```
Diagnostic err: Property "oneOf" is not expected to be here in path ["channels","persistent://platform2/event/interaction","publish","message","oneOf"] starting L17 C14, ending L26 C78
```
I was pretty sure that `oneOf` was supported for a `message`
Foe example
```
channels:
  "persistent://platform2/event/interaction":
    publish:
      message:
        oneOf:
          - $ref: '../messages/messages.yml#/components/messages/endpointClosed'
          - $ref: '../messages/messages.yml#/components/messages/endpointCreated'
          - $ref: '../messages/messages.yml#/components/messages/endpointOpened'
          - $ref: '../messages/messages.yml#/components/messages/interactionClosed'
          - $ref: '../messages/messages.yml#/components/messages/interactionCreated'
          - $ref: '../messages/messages.yml#/components/messages/interactionOpened'
          - $ref: '../messages/messages.yml#/components/messages/interactionSegmentInserted'
          - $ref: '../messages/messages.yml#/components/messages/intervalOpened'
          - $ref: '../messages/messages.yml#/components/messages/intervalNext'
```
but when I remove 
```
          - $ref: '../messages/messages.yml#/components/messages/intervalNext'
```
ALL the errors go away - so not really sure how to debug this if some of the errors are "false leads".

Any advice as to find which error is the root cause? Thanks!
